In [28]:
import numpy as np

# Define a 3x3 matrix with my "0"s and friend's "1"s
def calculate_determinant(matrix):
    return int(np.linalg.det(matrix))

# Example: I place "0" on the diagonal, and my friend places "1" elsewhere
matrix = np.array([[0, 1, 1],
                   [1, 0, 1],
                   [1, 1, 0]])

det = calculate_determinant(matrix)
print(f"Matrix:\n{matrix}\nDeterminant: {det}")


Matrix:
[[0 1 1]
 [1 0 1]
 [1 1 0]]
Determinant: 2


In [29]:
from itertools import product

# Generate all possible 3x3 matrices with my "0"s and my friend's "1"s
def generate_matrices(n):
    for entries in product([0, 1], repeat=n*n):
        yield np.array(entries).reshape(n, n)

# Check which matrices yield a zero determinant
zero_determinant_matrices = []
for matrix in generate_matrices(3):
    if calculate_determinant(matrix) == 0:
        zero_determinant_matrices.append(matrix)

print(f"Number of zero-determinant matrices: {len(zero_determinant_matrices)}")
for matrix in zero_determinant_matrices:
    print(matrix, "\n")


Number of zero-determinant matrices: 338
[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[[0 0 0]
 [0 0 0]
 [0 0 1]] 

[[0 0 0]
 [0 0 0]
 [0 1 0]] 

[[0 0 0]
 [0 0 0]
 [0 1 1]] 

[[0 0 0]
 [0 0 0]
 [1 0 0]] 

[[0 0 0]
 [0 0 0]
 [1 0 1]] 

[[0 0 0]
 [0 0 0]
 [1 1 0]] 

[[0 0 0]
 [0 0 0]
 [1 1 1]] 

[[0 0 0]
 [0 0 1]
 [0 0 0]] 

[[0 0 0]
 [0 0 1]
 [0 0 1]] 

[[0 0 0]
 [0 0 1]
 [0 1 0]] 

[[0 0 0]
 [0 0 1]
 [0 1 1]] 

[[0 0 0]
 [0 0 1]
 [1 0 0]] 

[[0 0 0]
 [0 0 1]
 [1 0 1]] 

[[0 0 0]
 [0 0 1]
 [1 1 0]] 

[[0 0 0]
 [0 0 1]
 [1 1 1]] 

[[0 0 0]
 [0 1 0]
 [0 0 0]] 

[[0 0 0]
 [0 1 0]
 [0 0 1]] 

[[0 0 0]
 [0 1 0]
 [0 1 0]] 

[[0 0 0]
 [0 1 0]
 [0 1 1]] 

[[0 0 0]
 [0 1 0]
 [1 0 0]] 

[[0 0 0]
 [0 1 0]
 [1 0 1]] 

[[0 0 0]
 [0 1 0]
 [1 1 0]] 

[[0 0 0]
 [0 1 0]
 [1 1 1]] 

[[0 0 0]
 [0 1 1]
 [0 0 0]] 

[[0 0 0]
 [0 1 1]
 [0 0 1]] 

[[0 0 0]
 [0 1 1]
 [0 1 0]] 

[[0 0 0]
 [0 1 1]
 [0 1 1]] 

[[0 0 0]
 [0 1 1]
 [1 0 0]] 

[[0 0 0]
 [0 1 1]
 [1 0 1]] 

[[0 0 0]
 [0 1 1]
 [1 1 0]] 

[[0 0 0]
 [0 1 1]
 [1 1 1]] 


In [30]:
# Analyze characteristics of zero-determinant matrices
def analyze_zero_determinant_matrices(zero_determinant_matrices):
    row_zero_count = 0
    col_zero_count = 0
    diag_zero_count = 0

    for matrix in zero_determinant_matrices:
        # Check if any row is all zeros
        if any(np.all(row == 0) for row in matrix):
            row_zero_count += 1

        # Check if any column is all zeros
        if any(np.all(col == 0) for col in matrix.T):
            col_zero_count += 1

        # Check if all diagonal elements are zeros
        if np.all(np.diag(matrix) == 0):
            diag_zero_count += 1

    return row_zero_count, col_zero_count, diag_zero_count

# Run the analysis
row_zero_count, col_zero_count, diag_zero_count = analyze_zero_determinant_matrices(zero_determinant_matrices)

print(f"Number of matrices with a row of all zeros: {row_zero_count}")
print(f"Number of matrices with a column of all zeros: {col_zero_count}")
print(f"Number of matrices with zeros on the diagonal: {diag_zero_count}")


Number of matrices with a row of all zeros: 169
Number of matrices with a column of all zeros: 169
Number of matrices with zeros on the diagonal: 49


In [31]:
# Analyze the ranks of zero-determinant matrices
def analyze_matrix_ranks(zero_determinant_matrices):
    dependent_matrices = 0
    for matrix in zero_determinant_matrices:
        rank = np.linalg.matrix_rank(matrix)
        if rank < matrix.shape[0]:  # Check if rank is less than n
            dependent_matrices += 1
    return dependent_matrices

# Run the rank analysis
dependent_matrices = analyze_matrix_ranks(zero_determinant_matrices)

print(f"Number of zero-determinant matrices with linear dependence: {dependent_matrices}")


Number of zero-determinant matrices with linear dependence: 338


In [32]:
# Simulate n x n matrix game and analyze strategies for forcing linear dependence
def simulate_matrix_game(n):
    from itertools import product

    zero_determinant_count = 0
    linear_dependence_count = 0

    # Generate all possible n x n matrices
    for entries in product([0, 1], repeat=n*n):
        matrix = np.array(entries).reshape(n, n)
        det = np.linalg.det(matrix)
        rank = np.linalg.matrix_rank(matrix)

        # Count matrices with zero determinant and linear dependence
        if det == 0:
            zero_determinant_count += 1
            if rank < n:
                linear_dependence_count += 1

    return zero_determinant_count, linear_dependence_count

# Simulate for n = 4
n = 4
zero_det_count, linear_dep_count = simulate_matrix_game(n)

print(f"n = {n}")
print(f"Number of zero-determinant matrices: {zero_det_count}")
print(f"Number of matrices with linear dependence: {linear_dep_count}")


n = 4
Number of zero-determinant matrices: 42976
Number of matrices with linear dependence: 42976
